mod tree;
use tree::binary_tree::HuffmanCoder;


fn main() {

    let src = "asdadksadfkjhkkliqweirqewnrwqjalskdflasjdfklahksdfkhsdkjfhkjahdfsjkahdfkasdfjaisdfjailsijfdnkkcnadkncknjaskjflasjdfasdfljalksdjflasjfdlajsfdlajsdfljasdlfjalsfjdlkajsdflkajsflkdjaskldfjlkasdjfklasjdfklajsfdlkasdfasdadksadfkjhkkliqweirqewnrwqjalskdflasjdfklahksdfkhsdkjfhkjahdfsjkahdfkasdfjaisdfjailsijfdnkkcnadkncknjaskjflasjdfasdfljalksdjflasjfdlajsfdlajsdfljasdlfjalsfjdlkajsdflkajsflkdjaskldfjlkasdjfklasjdfklajsfdlkasdfasdadksadfkjhkkliqweirqewnrwqjalskdflasjdfklahksdfkhsdkjfhkjahdfsjkahdfkasdfjaisdfjailsijfdnkkcnadkncknjaskjflasjdfasdfljalksdjflasjfdlajsfdlajsdfljasdlfjalsfjdlkajsdflkajsflkdjaskldfjlkasdjfklasjdfklajsfdlkasdfasdadksadfkjhkkliqweirqewnrwqjalskdflasjdfklahksdfkhsdkjfhkjahdfsjkahdfkasdfjaisdfjailsijfdnkkcnadkncknjaskjflasjdfasdfljalksdjflasjfdlajsfdlajsdfljasdlfjalsfjdlkajsdflkajsflkdjaskldfjlkasdjfklasjdfklajsfdlkasdfasdadksadfkjhkkliqweirqewnrwqjalskdflasjdfklahksdfkhsdkjfhkjahdfsjkahdfkasdfjaisdfjailsijfdnkkcnadkncknjaskjflasjdfasdfljalksdjflasjfdlajsfdlajsdfljasdlfjalsfjdlkajsdflkajsflkdjaskldfjlkasdjfklasjdfklajsfdlkasdfasdadksadfkjhkkliqweirqewnrwqjalskdflasjdfklahksdfkhsdkjfhkjahdfsjkahdfkasdfjaisdfjailsijfdnkkcnadkncknjaskjflasjdfasdfljalksdjflasjfdlajsfdlajsdfljasdlfjalsfjdlkajsdflkajsflkdjaskldfjlkasdjfklasjdfklajsfdlkasdfasdadksadfkjhkkliqweirqewnrwqjalskdflasjdfklahksdfkhsdkjfhkjahdfsjkahdfkasdfjaisdfjailsijfdnkkcnadkncknjaskjflasjdfasdfljalksdjflasjfdlajsfdlajsdfljasdlfjalsfjdlkajsdflkajsflkdjaskldfjlkasdjfklasjdfklajsfdlkasdfasdadksadfkjhkkliqweirqewnrwqjalskdflasjdfklahksdfkhsdkjfhkjahdfsjkahdfkasdfjaisdfjailsijfdnkkcnadkncknjaskjflasjdfasdfljalksdjflasjfdlajsfdlajsdfljasdlfjalsfjdlkajsdflkajsflkdjaskldfjlkasdjfklasjdfklajsfdlkasdfasdadksadfkjhkkliqweirqewnrwqjalskdflasjdfklahksdfkhsdkjfhkjahdfsjkahdfkasdfjaisdfjailsijfdnkkcnadkncknjaskjflasjdfasdfljalksdjflasjfdlajsfdlajsdfljasdlfjalsfjdlkajsdflkajsflkdjaskldfjlkasdjfklasjdfklajsfdlkasdfasdadksadfkjhkkliqweirqewnrwqjalskdflasjdfklahksdfkhsdkjfhkjahdfsjkahdfkasdfjaisdfjailsijfdnkkcnadkncknjaskjflasjdfasdfljalksdjflasjfdlajsfdlajsdfljasdlfjalsfjdlkajsdflkajsflkdjaskldfjlkasdjfklasjdfklajsfdlkasdfasdadksadfkjhkkliqweirqewnrwqjalskdflasjdfklahksdfkhsdkjfhkjahdfsjkahdfkasdfjaisdfjailsijfdnkkcnadkncknjaskjflasjdfasdfljalksdjflasjfdlajsfdlajsdfljasdlfjalsfjdlkajsdflkajsflkdjaskldfjlkasdjfklasjdfklajsfdlkasdf";
    let mut coder = HuffmanCoder::new(src);
    let result = coder.ecode(src);
    println!("{:#?} = {:#?}", src, result);



}




